# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('history', models.TextField(primary_key=True, serialize=False, verbose_name='تاریخچه')),
                ('chart', models.CharField(max_length=30, verbose_name='چارت سازمانی')),
                ('goals', models.TextField(verbose_name='اهداف')),
                ('activities', models.TextField(verbose_name='فعالیت\u200cها')),
                ('supporters', models.TextField(verbose_name='حمایت\u200cکننده\u200cها')),
            ],
            options={
                'verbose_name': 'اطلاع کلان سامانه',
                'verbose_name_plural': 'اطلاعات کلان سامانه',
            },
        ),
    ]
