# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('history', models.TextField(primary_key=True, serialize=False)),
                ('chart', models.CharField(max_length=30)),
                ('goals', models.TextField()),
                ('activities', models.TextField()),
                ('supporters', models.TextField()),
            ],
        ),
    ]
