# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='active_user',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='active_user',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='active_user',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
