# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر'),
        ),
    ]
