# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0002_auto_20171204_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_user',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='active_user',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
