# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-01 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0002_auto_20180201_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamyar_madadjoo_payment',
            name='need',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='active_user.requirements'),
            preserve_default=False,
        ),
    ]
