# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0002_auto_20180201_1109'),
        ('active_user', '0003_hamyar_madadjoo_payment_need'),
    ]

    operations = [
    ]
