# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0003_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madadjoo',
            name='corr_madadkar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='active_user.madadkar', verbose_name='مددجوی حمایت\u200cکننده'),
        ),
    ]
