# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0003_auto_20171204_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_user',
            name='id_number',
            field=models.IntegerField(unique=True),
        ),
    ]
