# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 08:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0004_auto_20171204_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='hamyar',
            fields=[
                ('active_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('active_user.active_user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='madadjoo',
            fields=[
                ('active_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(null=True)),
                ('edu_status', models.TextField(null=True)),
                ('successes', models.TextField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('invest_percentage', models.FloatField(default=0.0, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('active_user.active_user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='madadkar',
            fields=[
                ('active_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('active_user.active_user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='madadjoo',
            name='corr_madadkar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_user.madadkar'),
        ),
    ]
