# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-02 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0004_merge_20180202_1629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='removed_sponsership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='removed_sponsership',
            name='hamyar',
        ),
        migrations.RemoveField(
            model_name='removed_sponsership',
            name='madadjoo',
        ),
        migrations.DeleteModel(
            name='removed_sponsership',
        ),
    ]
