# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-26 18:11
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0005_auto_20180125_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='madadjoo_madadkar_letter',
            name='thank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='madadjoo_madadkar_letter',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='active_user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
