# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0005_auto_20180202_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_madadjoo_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('mo', 'monthly'), ('ann', 'annual'), ('inst', 'instantly')], max_length=60)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_user.admin_user')),
                ('madadjoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_user.madadjoo')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_user.requirements')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='admin_madadjoo_payment',
            unique_together=set([('madadjoo', 'admin', 'date')]),
        ),
    ]
