# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0006_auto_20180127_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='description',
            field=models.TextField(default='شرح نیاز ثبت نشده است.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirements',
            name='type',
            field=models.CharField(choices=[('mo', 'monthly'), ('ann', 'annual'), ('inst', 'instantly')], max_length=60, null=True),
        ),
    ]
