# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-26 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0006_auto_20180126_1811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='madadjoo_madadkar_letter',
            unique_together=set([]),
        ),
    ]
