# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-26 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0007_auto_20180126_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='madadjoo_hamyar_letter',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
