# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0008_add_madadjoo_admin_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='urgent_need_admin_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('madadjoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_user.madadjoo')),
                ('madadkar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_user.madadkar')),
            ],
        ),
        migrations.AlterField(
            model_name='hamyar_madadjoo_non_cash',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='madadkar_remove_madadjoo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
