# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-28 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0007_auto_20180127_1726'),
        ('active_user', '0009_auto_20180126_2005'),
    ]

    operations = [
    ]
