# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0009_auto_20180129_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgent_need_admin_letter',
            name='need',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='active_user.requirements'),
            preserve_default=False,
        ),
    ]
