# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0010_urgent_need_admin_letter_need'),
    ]

    operations = [
        migrations.CreateModel(
            name='warning_admin_letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_user.admin_user')),
                ('madadkar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_user.madadkar')),
            ],
        ),
    ]
