# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0010_merge_20180128_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madadkar_remove_madadjoo',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='hamyar_madadjoo_meeting',
            unique_together=set([('hamyar', 'date', 'madadjoo')]),
        ),
        migrations.AlterUniqueTogether(
            name='hamyar_madadjoo_payment',
            unique_together=set([('madadjoo', 'hamyar', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='hamyar_system_payment',
            unique_together=set([('hamyar', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='madadjoo_hamyar_letter',
            unique_together=set([('hamyar', 'date', 'madadjoo')]),
        ),
        migrations.AlterUniqueTogether(
            name='madadjoo_madadkar_letter',
            unique_together=set([('madadjoo', 'date')]),
        ),
    ]
