# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0011_warning_admin_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamyar_madadjoo_meeting',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='madadkar_remove_madadjoo',
            name='madadkar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='active_user.madadkar'),
        ),
    ]
