# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0012_merge_20180129_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamyar_madadjoo_non_cash',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
