# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0012_auto_20180129_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='substitute_a_madadjoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('remove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_user.madadkar_remove_madadjoo')),
                ('substituted_madadjoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='active_user.madadjoo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='substitute_a_madadjoo',
            unique_together=set([('remove', 'substituted_madadjoo')]),
        ),
    ]
