# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-29 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0013_auto_20180129_0811'),
        ('active_user', '0010_urgent_need_admin_letter_need'),
    ]

    operations = [
    ]
