# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0014_merge_20180129_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamyar_madadjoo_meeting',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
