# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-29 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0015_hamyar_madadjoo_meeting_confirmed'),
        ('active_user', '0011_warning_admin_letter'),
    ]

    operations = [
    ]
