# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_user', '0016_merge_20180129_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madadkar_remove_madadjoo',
            name='madadkar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='active_user.madadkar'),
        ),
    ]
